POST http://localhost:3000/novo-filme
Content-Type: application/json

  {
    "name": "clube da luta",
    "gender": "ação",
    "duration": 150,
    "classification": 18
  }

###

GET http://localhost:3000/listar-filmes

###

DELETE http://localhost:3000/deletar-filme/6

###
PUT http://localhost:3000/editar-filme/7
Content-Type: application/json

{
    "name": "Homem de ferro",
    "gender": "ação",
    "duration": 300, 
    "classification": 12
}
