POST http://localhost:3000/novo-filme
Content-Type: application/json

  {
    "name": "neguinho",
    "gender": "neguinho",
    "duration": 1,
    "classification": "N"
  }

###

GET http://localhost:3001/list-films

###

DELETE http://localhost:3000/deletar-filme/6

{
    "id": 108,
    "name": "neguinho",
    "duration": "1",
    "classification": "N",
    "gender": "neguinho"
  }

###
PUT http://localhost:3000/editar-filme/7
Content-Type: application/json

{
    "id": 108,
    "name": "neguinho",
    "duration": "2",
    "classification": "N",
    "gender": "neguinho"
  }
